"""course dates

Revision ID: 719ad95e08f9
Revises: 8349f166b6e5
Create Date: 2026-09-23 20:51:00.562696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719ad95e08f9'
down_revision: Union[str, None] = '8349f166b6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable primero: los cursos existentes se rellenan con las fechas de su año
    # académico antes de exigir NOT NULL, para no romper filas ya sembradas/reales.
    op.add_column('courses', sa.Column('starts_on', sa.Date(), nullable=True))
    op.add_column('courses', sa.Column('ends_on', sa.Date(), nullable=True))
    op.execute(
        """
        UPDATE courses
        SET starts_on = academic_years.starts_on,
            ends_on = academic_years.ends_on
        FROM academic_years
        WHERE courses.academic_year_id = academic_years.id
        """
    )
    op.alter_column('courses', 'starts_on', nullable=False)
    op.alter_column('courses', 'ends_on', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'ends_on')
    op.drop_column('courses', 'starts_on')
    # ### end Alembic commands ###
